name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.PROFILE_METRICS_TOKEN }}
          filename: resources/github-metrics.*
          committer_branch: ${{ github.ref_name }}

      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: resources/metrics.plugin.isocalendar.svg
          token: ${{ secrets.PROFILE_METRICS_TOKEN }}
          committer_branch: ${{ github.ref_name }}
          base: ""
          plugin_isocalendar: yes
