name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
