name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: resources/general-metrics.svg
          token: ${{ secrets.PROFILE_METRICS_TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar
          plugin_isocalendar: yes

      - name: Language
        uses: lowlighter/metrics@latest
        with:
          filename: resources/language-metrics.svg
          token: ${{ secrets.PROFILE_METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_recent_days: 365
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css, ruby
